import { Inter } from "next/font/google";
import HeaderBar from "./components/Header";
import Container from "@mui/material/Container";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import useAuth from '../hooks/useAuth';
import "./globals.css";
import dynamic from 'next/dynamic';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Dear Therapist",
  description: "Generated by Dear Therapist",
};

const DynamicHeaderBar = dynamic(() => import('./components/Header'), {
  ssr: false,
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DynamicHeaderBar />
        <AppRouterCacheProvider>
          <Container>
            {children}
          </Container>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}