import { Inter } from "next/font/google";
import HeaderBar from "./components/Header";
import Container from "@mui/material/Container";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import useAuth from '../hooks/useAuth';
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Dear Therapist",
  description: "Generated by Dear Therapist",
};

export default function RootLayout({ children }) {
  const { user } = useAuth();

  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderBar user={user} />
        <AppRouterCacheProvider>
          <Container>
            {children}
          </Container>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
